Package ‘MachineShop’
February 15, 2019
Type Package
Title Machine Learning Models and Tools
Version 1.2.0
Date 2019-02-15
Author Brian J Smith [aut, cre]
Maintainer Brian J Smith <brian-j-smith@uiowa.edu>

#### Description
 Meta-package for statistical and machine learning with a common interface for model fitting,
prediction, performance assessment, and presentation of results. Supports predictive modeling
of numerical, categorical, and censored time-to-event outcomes and resample (bootstrap
and cross-validation) estimation of model performance.
Imports abind, foreach, ggplot2, Hmisc, kernlab, magrittr, methods,
party, polspline, recipes (>= 0.1.4), rsample, Rsolnp,
survival, utils
Suggests adabag, BART, bartMachine, C50, doParallel, e1071, earth,
gbm, glmnet, kableExtra, kknn, knitr, lars, mda, MASS, mboost,
nnet, partykit, pls, randomForest, ranger, rmarkdown, rms,
rpart, testthat, tree, xgboost
License GPL-3
URL https://brian-j-smith.github.io/MachineShop/
BugReports https://github.com/brian-j-smith/MachineShop/issues
RoxygenNote 6.1.1
VignetteBuilder knitr
NeedsCompilation no
Repository CRAN
Date/Publication 2019-02-15 16:20:03 UTC
R topics documented:
MachineShop-package         . . 
            5
1
2 R topics documented:
AdaBagModel           6
AdaBoostModel          . . . 7
BARTMachineModel          8
BARTModel           . 10
BlackBoostModel          . . 11
C50Model           . . 13
calibration           . . 14
CForestModel           15
confusion           . . 16
CoxModel           . . 17
dependence           . 18
diff            . . 19
EarthModel           . 20
expand.model           21
FDAModel           . 22
fit            . . 23
GAMBoostModel          . . 24
GBMModel           . 25
GLMBoostModel          . . 26
GLMModel           . 28
GLMNetModel          . . . 29
Grid            0
KNNModel           1
LARSModel           2
LDAModel           3
lift            . 4
LMModel           . 5
MDAModel           5
metricinfo           . 7
metrics            37
MLControl           9
MLMetric           . . 41
MLModel           . . 42
ModelFrame           . 44
modelinfo           . . 45
NaiveBayesModel          . . 46
NNetModel           . 46
performance           . 48
performance_curve          . 49
plot            . 50
PLSModel           . . 52
POLRModel           . 53
predict            54
QDAModel           . 55
RandomForestModel          56
RangerModel           57
resample           . . . 58
response           . . . 60
MachineShop-package 3
RPartModel           . 60
StackedModel           62
summary           . . 63
SuperModel           . 64
SurvMatrix           . 65
SurvRegModel          . . . 66
SVMModel           . 67
t.test            . 69
TreeModel           . . 70
tune            . 71
varimp            73
XGBModel           . 74
Index 76
MachineShop-package MachineShop: Machine Learning Models and Tools

#### Description

Meta-package for statistical and machine learning with a common interface for model fitting, prediction,
performance assessment, and presentation of results. Supports predictive modeling of
numerical, categorical, and censored time-to-event outcomes and resample (bootstrap and crossvalidation)
estimation of model performance.

#### Details

MachineShop provides a unified interface to machine learning and statistical models provided by
other packages. Supported models are summarized in the table below according to the types of
response variables with which each can be used. Additional model information can be obtained
with the modelinfo function.
Model Objects Categorical Continuous Survival
AdaBagModel f
AdaBoostModel f
BARTModel f n S
BARTMachineModel b n
BlackBoostModel b n S
C50Model f
CForestModel f n S
CoxModel S
EarthModel f n
FDAModel f
GAMBoostModel b n S
GBMModel f n S
GLMBoostModel b n S
GLMModel b n
GLMNetModel f m,n S
4 MachineShop-package
KNNModel f,o n
LARSModel n
LDAModel f
LMModel f m,n
MDAModel f
NaiveBayesModel f
NNetModel f n
PDAModel f
PLSModel f n
POLRModel o
QDAModel f
RandomForestModel f n
RangerModel f n S
RPartModel f n S
StackedModel f,o m,n S
SuperModel f,o m,n S
SurvRegModel S
SVMModel f n
TreeModel f n
XGBModel f n
Categorical: b = binary, f = factor, o = ordered; Continuous: m = matrix, n = numeric; Survival: S
= Surv
The following set of standard model training, prediction, performance assessment, and tuning functions
are available for the model objects.
Training:
fit Model Fitting
resample Resample Estimation of Model Performance
tune Model Tuning and Selection
Prediction:
predict Model Prediction
Performance Assessment:
calibration Model Calibration
confusion Confusion Matrix
dependence Parital Dependence
diff Model Performance Differences
lift Lift Curves
performance Model Performance Metrics
performance_curve Model Performance Curves
. 5
varimp Variable Importance
Methods for resample estimation include
BootControl Simple Bootstrap
CVControl Repeated K-Fold Cross-Validation
OOBControl Out-of-Bootstrap
SplitControl Split Training-Testing
TrainControl Training Resubstitution
Tabular and graphical summaries of modeling results can be obtained with
summary
plot
Custom metrics and models can be created with the MLMetric and MLModel constructors.
Author(s)
Maintainer: Brian J Smith <brian-j-smith@uiowa.edu>
See Also
Useful links:
• https://brian-j-smith.github.io/MachineShop/
• Report bugs at https://github.com/brian-j-smith/MachineShop/issues
. Quote Operator

#### Description

Shorthand notation for the quote function. The quote operator simply returns its argument unevaluated
and can be applied to any R expression. Useful for calling model constructors with quoted
parameter values that are defined in terms of a model formula, data, weights, nobs, nvars, or y.

#### Usage
<pre><code>

.(expr)

</code></pre>
####Arguments

expr any syntactically valid R expression.
6 AdaBagModel

#### Value

The quoted (unevaluated) expression.
See Also
quote

#### Examples
```{r}

## Stepwise variable selection with BIC
library(MASS)
glmfit <- fit(medv ~ ., Boston, GLMStepAICModel(k = .(log(nobs))))
varimp(glmfit)
```






