BlackBoostModel Gradient Boosting with Regression Trees

#### Description

Gradient boosting for optimizing arbitrary loss functions where regression trees are utilized as baselearners.

#### Usage
<pre><code>

BlackBoostModel(family = NULL, mstop = 100, nu = 0.1,
risk = c("inbag", "oobag", "none"), stopintern = FALSE,
trace = FALSE, teststat = c("quadratic", "maximum"),
testtype = c("Teststatistic", "Univariate", "Bonferroni",
"MonteCarlo"), mincriterion = 0, minsplit = 10, minbucket = 4,
maxdepth = 2, saveinfo = FALSE, ...)
12 BlackBoostModel

</code></pre>
####Arguments

family Family object. Set automatically according to the class type of the response
variable.
* ``mstop``: number of initial boosting iterations.
nu step size or shrinkage parameter between 0 and 1.
risk method to use in computing the empirical risk for each boosting iteration.
stopintern logical inidicating whether the boosting algorithm stops internally when the outof-
bag risk increases at a subsequent iteration.
trace logical indicating whether status information is printed during the fitting process.
* teststat type of the test statistic to be applied for variable selection.
* testtype how to compute the distribution of the test statistic.
* mincriterion value of the test statistic or 1 - p-value that must be exceeded in order to implement
a split.
* minsplit minimum sum of weights in a node in order to be considered for splitting.
* minbucket minimum sum of weights in a terminal node.
* maxdepth maximum depth of the tree.
* saveinfo logical indicating whether to store information about variable selection in info slot of each partynode.
... additional arguments to ctree_control.
Details
Response Types: binary, numeric, Surv
Automatic Tuning Grid Parameters: mstop, maxdepth
Default values for the NULL arguments and further model details can be found in the source links
below.

#### Value

MLModel class object.
See Also
blackboost, Family, ctree_control, fit, resample, tune

#### Examples
```{r}

library(MASS)
fit(type ~ ., data = Pima.tr, model = BlackBoostModel())

```
