
LDAModel Linear Discriminant Analysis Model

#### Description

Performs linear discriminant analysis.

#### Usage
<pre><code>

LDAModel(prior = NULL, tol = 1e-04, method = c("moment", "mle",
"mve", "t"), nu = 5, dimen = NULL, use = c("plug-in", "debiased",
"predictive"))

</code></pre>
####Arguments

prior prior probabilities of class membership if specified or the class proportions in
the training set otherwise.
tol tolerance for the determination of singular matrices.
method type of mean and variance estimator.
nu degrees of freedom for method = "t".
dimen dimension of the space to use for prediction.
use type of parameter estimation to use for prediction.
Details
Response Types: factor
Automatic Tuning Grid Parameters: dimen
The predict function for this model additionally accepts the following argument.
prior prior class membership probabilities for prediction data if different from the training set.
Default values for the NULL arguments and further model details can be found in the source links
below.

#### Value

MLModel class object.
See Also
lda, predict.lda, fit, resample, tune
34 lift

#### Examples
```{r}

fit(Species ~ ., data = iris, model = LDAModel())
```
