48 performance
performance Model Performance Metrics

#### Description

Compute measures of model performance.

#### Usage
<pre><code>

performance(x, ...)
## S3 method for class 'Resamples'
performance(x, ..., na.rm = TRUE)
## S3 method for class 'factor'
performance(x, y, metrics = c(Brier =
MachineShop::brier, Accuracy = MachineShop::accuracy, Kappa =
MachineShop::kappa2, `Weighted Kappa` = MachineShop::weighted_kappa2,
ROCAUC = MachineShop::roc_auc, Sensitivity = MachineShop::sensitivity,
Specificity = MachineShop::specificity), cutoff = 0.5, ...)
## S3 method for class 'matrix'
performance(x, y, metrics = c(RMSE = MachineShop::rmse,
R2 = MachineShop::r2, MAE = MachineShop::mae), ...)
## S3 method for class 'numeric'
performance(x, y, metrics = c(RMSE = MachineShop::rmse,
R2 = MachineShop::r2, MAE = MachineShop::mae), ...)
## S3 method for class 'Surv'
performance(x, y, metrics = c(CIndex =
MachineShop::cindex, Brier = MachineShop::brier, ROCAUC =
MachineShop::roc_auc, Accuracy = MachineShop::accuracy), cutoff = 0.5,
...)
## S3 method for class 'Confusion'
performance(x, ...)
## S3 method for class 'ConfusionMatrix'
performance(x, metrics = c(Accuracy =
MachineShop::accuracy, Kappa = MachineShop::kappa2), ...)

</code></pre>
####Arguments

x observed responses or class containing observed and predicted responses.
... arguments passed from the Resamples method to the response type-specific
methods or from the method for Confusion to ConfusionMatrix.
performance_curve 49
na.rm logical indicating whether to remove observed or predicted responses that are
NA when calculating metrics.
y predicted responses.
metrics function, one or more function names, or list of named functions to include in
the calculation of performance metrics.
cutoff threshold above which binary factor probabilities are classified as events and
below which survival probabilities are classified.
See Also
response, predict, resample, confusion, metrics, plot, summary

#### Examples
```{r}

res <- resample(Species ~ ., data = iris, model = GBMModel)
(perf <- performance(res))
summary(perf)
plot(perf)
## Survival response example
library(survival)
library(MASS)
fo <- Surv(time, status != 2) ~ sex + age + year + thickness + ulcer
gbmfit <- fit(fo, data = Melanoma, model = GBMModel)
obs <- response(fo, data = Melanoma)
pred <- predict(gbmfit, newdata = Melanoma, type = "prob")
performance(obs, pred)
```
