
summary Model Performance Summary

#### Description

Summary statistics for resampled model performance metrics.

#### Usage
<pre><code>

## S3 method for class 'Performance'
summary(object, stats = c(Mean = base::mean, Median
= stats::median, SD = stats::sd, Min = base::min, Max = base::max),
na.rm = TRUE, ...)
## S3 method for class 'Resamples'
summary(object, stats = c(Mean = base::mean, Median =
stats::median, SD = stats::sd, Min = base::min, Max = base::max),
na.rm = TRUE, ...)
## S3 method for class 'MLModelTune'
summary(object, stats = c(Mean = base::mean, Median
= stats::median, SD = stats::sd, Min = base::min, Max = base::max),
na.rm = TRUE, ...)
## S3 method for class 'Confusion'
summary(object, ...)
## S3 method for class 'ConfusionMatrix'
summary(object, ...)
## S3 method for class 'Curves'
summary(object, stat = base::mean, ...)

</code></pre>
####Arguments

object object to summarize.
stats function, one or more function names, or list of named functions to include in
the calculation of summary statistics.
na.rm logical indicating whether to exclude missing values.
... arguments passed to other methods.
stat function to compute a summary statistic at each cutoff value of resampled metrics
in Curves, or NULL for resample-specific metrics.

#### Value

array with summmary statistics in the second dimension, metrics in the first for single models, and
models and metrics in the first and third, respectively, for multiple models.
64 SuperModel
See Also
performance, resample, diff, tune, confusion

#### Examples
```{r}

## Factor response example
fo <- Species ~ .
control <- CVControl()
gbmres1 <- resample(fo, iris, GBMModel(n.trees = 25), control)
gbmres2 <- resample(fo, iris, GBMModel(n.trees = 50), control)
gbmres3 <- resample(fo, iris, GBMModel(n.trees = 100), control)
summary(gbmres3)
res <- Resamples(GBM1 = gbmres1, GBM2 = gbmres2, GBM3 = gbmres3)
summary(res)
```
