
SurvRegModel Parametric Survival Model

#### Description

Fits the accelerated failure time family of parametric survival models.

#### Usage
<pre><code>

SurvRegModel(dist = c("weibull", "exponential", "gaussian", "logistic",
"lognormal", "logloglogistic"), scale = NULL, parms = NULL, ...)
SurvRegStepAICModel(dist = c("weibull", "exponential", "gaussian",
"logistic", "lognormal", "logloglogistic"), scale = NULL,
parms = NULL, ..., direction = c("both", "backward", "forward"),
scope = NULL, k = 2, trace = FALSE, steps = 1000)

</code></pre>
####Arguments

dist assumed distribution for y variable.
scale optional fixed value for the scale.
parms a list of fixed parameters.
... arguments passed to survreg.control.
direction mode of stepwise search, can be one of "both" (default), "backward", or "forward".
scope defines the range of models examined in the stepwise search. This should be a
list containing components upper and lower, both formulae.
k multiple of the number of degrees of freedom used for the penalty. Only k = 2
gives the genuine AIC: k = log(nobs) is sometimes referred to as BIC or SBC.
trace if positive, information is printed during the running of stepAIC. Larger values
may give more information on the fitting process.
* ``steps``:  maximum number of steps to be considered.
Details
Response Types: Surv
Default values for the NULL arguments and further model details can be found in the source link
below.
SVMModel 67

#### Value

MLModel class object.
See Also
psm, survreg, survreg.control, stepAIC, fit, resample, tune
stepAIC, fit, resample, tune

#### Examples
```{r}

library(survival)
library(MASS)
fit(Surv(time, status != 2) ~ sex + age + year + thickness + ulcer,
data = Melanoma, model = SurvRegModel())

```
