SurvMatrix SurvMatrix Class Constructor

#### Description

Create an object of predicted survival events or probabilites for use with metrics provided by the
MachineShop package.

#### Usage
<pre><code>

SurvEvents(object = numeric(), times = NULL)
SurvProbs(object = numeric(), times = NULL)
## S4 method for signature 'SurvMatrix,ANY,ANY,ANY'
x[i, j, ..., drop = FALSE]

</code></pre>
####Arguments

object matrix, or object that can be converted to one, of predicted survival events or
probabilities with columns and rows representing prediction times and cases,
respectively.
times numeric vector of the survival prediction times.
x object from which to extract elements.
i, j, ... indices specifying elements to extract.
drop logical indicating that the result be returned as a numeric coerced to the lowest
dimension possible if TRUE or as a 2-dimensional SurvMatrix object otherwise.
66 SurvRegModel

#### Value

Object that is of the same class as the constructor name and inherits from SurvMatrix. 
#### Examples
```{r}
 of
these objects are the predicted survival events and probabilities returned by the predict function.
See Also
metrics, predict
