
SVMModel Support Vector Machine Models

#### Description

Fits the well known C-svc, nu-svc, (classification) one-class-svc (novelty) eps-svr, nu-svr (regression)
formulations along with native multi-class classification formulations and the boundconstraint
SVM formulations.

#### Usage
<pre><code>

SVMModel(scaled = TRUE, type = NULL, kernel = c("rbfdot", "polydot",
"vanilladot", "tanhdot", "laplacedot", "besseldot", "anovadot",
"splinedot"), kpar = "automatic", C = 1, nu = 0.2, epsilon = 0.1,
cache = 40, tol = 0.001, shrinking = TRUE)
SVMANOVAModel(sigma = 1, degree = 1, ...)
SVMBesselModel(sigma = 1, order = 1, degree = 1, ...)
SVMLaplaceModel(sigma = NULL, ...)
SVMLinearModel(...)
SVMPolyModel(degree = 1, scale = 1, offset = 1, ...)
SVMRadialModel(sigma = NULL, ...)
SVMSplineModel(...)
SVMTanhModel(scale = 1, offset = 1, ...)
68 SVMModel

</code></pre>
####Arguments

scaled logical vector indicating the variables to be scaled.
type type of support vector machine.
kernel kernel function used in training and predicting.
kpar list of hyper-parameters (kernel parameters).
C cost of constraints violation defined as the regularization term in the Lagrange
formulation.
nu parameter needed for nu-svc, one-svc, and nu-svr.
epsilon parameter in the insensitive-loss function used for eps-svr, nu-svr and eps-bsvm.
cache cache memory in MB.
tol tolerance of termination criterion.
shrinking whether to use the shrinking-heuristics.
sigma inverse kernel width used by the ANOVA, Bessel, and Laplacian kernels.
degree degree of the ANOVA, Bessel, and polynomial kernel functions.
... arguments to be passed to SVMModel.
order order of the Bessel function to be used as a kernel.
scale scaling parameter of the polynomial and hyperbolic tangent kernels as a convenient
way of normalizing patterns without the need to modify the data itself.
offset offset used in polynomial and hyperbolic tangent kernels.
Details
Response Types: factor, numeric
Automatic Tuning Grid Parameters • SVMANOVAModel: C, degree
• SVMBesselModel: C, order, degree
• SVMLaplaceModel: C, sigma
• SVMLinearModel: C
• SVMPolyModel: C, degree, scale
• SVMRadialModel: C, sigma

</code></pre>
####Arguments
 kernel and kpar are automatically set by the kernel-specific constructor functions.
Default values for the NULL arguments and further model details can be found in the source link
below.

#### Value

MLModel class object.
See Also
ksvm, fit, resample, tune
t.test 69

#### Examples
```{r}

library(MASS)
fit(medv ~ ., data = Boston, model = SVMRadialModel())
```
