---
title: "cvTools R Package"
author: "Kevin O'Brien"
date: "8 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cvTools)
```


## Functions in cvTools: 


* ``cvTool``: Low-level function for cross-validation
* ``cvFolds``: Cross-validation folds
* ``accessors``: Access or set information on cross-validation results
* ``repCV``: Cross-validation for linear models
* ``densityplot.cv``: Kernel density plots of cross-validation results
* ``cost``: Prediction loss
* ``bwplot.cv``: Box-and-whisker plots of cross-validation results
* ``cvTools-package``: Cross-validation tools for regression models
* ``subset.cv``: Subsetting cross-validation results
* ``plot.cv``: Plot cross-validation results
* ``cvSelect``: Model selection based on cross-validation
* ``cvReshape``: Reshape cross-validation results
* ``summary.cv``: Summarize cross-validation results
* ``aggregate.cv``: Aggregate cross-validation results
* ``cvFit``: Cross-validation for model evaluation
* ``dotplot.cv``: Dot plots of cross-validation results
* ``cvTuning``: Cross-validation for tuning parameter selection
* ``xyplot.cv``: X-Y plots of cross-validation results




